//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L10n.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("L10n.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get data from Column {0}.
        /// </summary>
        public static string CE001 {
            get {
                return ResourceManager.GetString("CE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type must be of Type IList.
        /// </summary>
        public static string DA001 {
            get {
                return ResourceManager.GetString("DA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find list with entities to save.
        /// </summary>
        public static string DA002 {
            get {
                return ResourceManager.GetString("DA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference types in Table Valued Parameter are currently not supported.
        /// </summary>
        public static string DA003 {
            get {
                return ResourceManager.GetString("DA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle cartesian Produkt. Only one Collection is allowed to use as parameter if Table Valued Parameter are not in use.
        /// </summary>
        public static string DA004 {
            get {
                return ResourceManager.GetString("DA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing data have no instance.
        /// </summary>
        public static string DE001 {
            get {
                return ResourceManager.GetString("DE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different connections are in use.
        /// </summary>
        public static string DE002 {
            get {
                return ResourceManager.GetString("DE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add connection to internal Pool.
        /// </summary>
        public static string DL001 {
            get {
                return ResourceManager.GetString("DL001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No import catalogs exists. Cannot create fast access for Data Access Layer.
        /// </summary>
        public static string GE001 {
            get {
                return ResourceManager.GetString("GE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load instance for {0} data transfer object.
        /// </summary>
        public static string GE002 {
            get {
                return ResourceManager.GetString("GE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient number of parameter has been provided.
        /// </summary>
        public static string GE003 {
            get {
                return ResourceManager.GetString("GE003", resourceCulture);
            }
        }
    }
}
